export default {
  lanzouUrl: 'https://pc.woozooo.com',
  page: {
    home: '/mydisk.php',
    login: '/account.php?action=login',
  },
  api: {
    task: '/doupload.php',
  },
  // 大于 maxSize 按 splitSize 分割
  splitSize: '47m', // 错误7079 - Math.floor(50000000 / 1024 / 1024)
  maxSize: '95m', // Math.floor(100000000 / 1024 / 1024)
  signSuffix: '.lzy.zip',
  homeTempDir: '.lanzouyun',
  supportList: [
    'doc',
    'docx',
    'zip',
    'rar', // octet-stream
    'apk',
    'ipa',
    'txt',
    'exe',
    '7z',
    'e',
    'z',
    'ct',
    'ke',
    'cetrainer',
    'db',
    'tar',
    'pdf',
    'w3x',
    'epub',
    'mobi',
    'azw',
    'azw3',
    'osk',
    'osz',
    'xpa',
    'cpk',
    'lua',
    'jar',
    'dmg',
    'ppt',
    'pptx',
    'xls',
    'xlsx',
    'mp3',
    'ipa',
    'iso',
    'img',
    'gho',
    'ttf',
    'ttc',
    'txf',
    'dwg',
    'bat',
    'imazingapp',
    'dll',
    'crx',
    'xapk',
    'conf',
    'deb',
    'rp',
    'rpm',
    'rplib',
    'mobileconfig',
    'appimage',
    'lolgezi',
    'flac',
    'cad',
    'hwt',
    'accdb',
    'ce',
    'xmind',
    'enc',
    'bds',
    'bdi',
    'ssf',
    'it',
  ],
}
